apiVersion: v1
kind: Service
metadata:
  name: dchat-service-envoy
spec:
  type: ClusterIP
  selector:
    app: dchat-deploy-envoy
  ports:
    - name: tls
      port: 9443
      protocol: TCP
      targetPort: 9443
    - name: admin
      port: 9000
      protocol: TCP
      targetPort: 9000
  externalIPs:
    - 192.168.49.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dchat-deploy-envoy
spec:
  selector:
    matchLabels:
      app: dchat-deploy-envoy
  replicas: 1
  template:
    metadata:
      labels:
        app: dchat-deploy-envoy
    spec:
      containers:
        - image: 'dchat_envoyfrontproxy:1.0'
          imagePullPolicy: IfNotPresent
          name: dchat-deploy-envoy
          ports:
            - name: tls
              containerPort: 9443
