apiVersion: v1
kind: Service
metadata:
  name: dchat-service-serviceweb
spec:
  selector:
    app: dchat-deploy-serviceweb
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      name: dchat-service
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dchat-deploy-serviceweb
spec:
  selector:
    matchLabels:
      app: dchat-deploy-serviceweb
  replicas: 2
  template:
    metadata:
      labels:
        app: dchat-deploy-serviceweb
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: INFO
            - name: SSL_ENABLED
              value: "false"
          image: "distributedchat_demo:1.0"
          imagePullPolicy: IfNotPresent
          name: dchat-deploy-serviceweb
          ports:
            - containerPort: 8080
              name: dchat-service
              protocol: TCP
